name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: dependencies
      run: sudo apt-get install libncurses5-dev 
    - name: build
      run: make
    - name: clean
      run: make clean
